quarkus:
  datasource:
    db-kind: postgresql
    username: postgres
    password: muyun2024
    jdbc:
      url: jdbc:postgresql://localhost:54324/muyun
  banner:
    path: banner.txt

  management:
    enable-compression: true

  log:
    category:
      "org.jdbi":
        level: INFO

    level: INFO
    console:
      enable: true
      format: "%d{yyyy-MM-dd HH:mm:ss} %-5p [%c{3.}] (%t) %s%e%n"
    file:
      enable: false
      path: logs/muyun.log
      level: DEBUG
      format: "%d{yyyy-MM-dd HH:mm:ss} %-5p [%c{3.}] (%t) %s%e%n"
      rotation:
        file-suffix: .yyyy-MM-dd
        rotate-on-boot: true
